from typing import List, Dict, Optional, Any
from pydantic import BaseModel, ConfigDict, Field

class MatchExplanation(BaseModel):
    """
    Structured explainability output generated by Gemini via LangGraph
    for match decision-support.
    """
    strengths: list[str] = Field(
        description="2-4 concrete, evidence-backed reasons this manager fits the specific business context",
        min_length=2,
        max_length=4
    )
    concerns: list[str] = Field(
        description="1-3 potential trade-offs, limitations, or risk areas based on the requirements vs profile",
        min_length=1,
        max_length=3
    )
    missing_requirements: list[str] = Field(
        description="Required skills or domain experience explicitly missing or not found in the profile",
        default_factory=list
    )
    recommendation_verdict: str = Field(
        description="1-2 sentence balanced decision-support synthesis explaining fit and trade-offs"
    )

    model_config = ConfigDict(extra="ignore")


class ExplanationCard(BaseModel):
    """
    Structured decision card ready for client consumption following
    zero-hallucination and responsible AI audits.
    """
    manager_id: str = Field(description="Candidate manager identifier")
    overall_score: float = Field(description="Deterministic overall compatibility score (0-100)")
    factor_scores: Dict[str, float] = Field(description="Deterministic sub-factor breakdown")
    strengths: List[str] = Field(description="2-4 verified, evidence-backed candidate strengths")
    concerns: List[str] = Field(description="1-3 practical trade-offs and operational risks")
    missing_requirements: List[str] = Field(default_factory=list, description="Missing required skills/experience")
    verdict: str = Field(description="1-2 sentence balanced decision-support synthesis")

    model_config = ConfigDict(extra="allow")
